---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/repetitive_cfrp/repetitive_cfrp.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/164581/articles/212644/master/file/figures/repetitive_cfrp/repetitive_cfrp.png"
