---
version: 2
multicolumn: false
web-width: 200
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/high_current_setup/high_current_setup.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/164581/articles/212644/master/file/figures/high_current_setup/high_current_setup.png"
    folder_url: "/users/164581/articles/212644/master/folder/figures/high_current_setup"
